hack4impact/immigrant-defense-project

- PULL_REQUEST_TEMPLATE.md
- README.md
- app/__init__.py
- app/checklist/__init__.py
- app/checklist/views.py
- app/templates/checklist/index.html
> Adding checklist blueprint (blueprint + routes + template).
> UI Testing 🔥 
> Paired programmed with Ivan. (Merged in his changes from `checlist_blueprint`)
> Checklist blueprint

- app/__init__.py
- app/models/__init__.py
- app/models/reminder.py
- app/reminder/__init__.py
- app/reminder/forms.py
- app/reminder/views.py
- app/sms.py
- app/templates/reminder/form.html
- app/templates/reminder/index.html
- manage.py
- requirements.txt
- tests/test_sms.py
* Added `Reminder` model
* Added reminder views at `/reminder` and `/reminder/new`
* Add SMS scheduler
* Added `test_sms.py` for sending test SMS reminders (need to obtain a paid Twilio account first though and add the proper keys to `config.env`
> Text reminders

- app/models/documents.py
Opening a PR for Steven's `Document` model so Ivan and I can use the model in our task.
> Add Documents model

- app/checklist/forms.py
- app/checklist/views.py
- app/models/checklist.py
- app/templates/checklist/edit_checklist_item.html
- app/templates/checklist/index.html
I changed/refactored all of our previous checklist item code to fit default checklist item.
I ran the local host and made sure the behavior was as expected (no errors).
> Refactoring to default checklist item

- app/models/__init__.py
- app/models/document.py
2 be more python!!
recreated the database with no issues
> rename documents to document and alphabetize model imports

- app/models/__init__.py
i think i got it right this time!!
recreated the db
> fix model import order

- app/models/user.py
Fixes https://github.com/hack4impact/immigrant-defense-project/issues/18
Ran `python manage.py recreate_db`
> insert roles when generating fake users

- app/models/checklist.py
- manage.py
Generate fake default checklist items and user checklist items
works if the breaking code in `user.py` (with `ApplicantProfile.generate_fake()` not being defined yet) is commented out)
> add generate_fake() functions for DefaultChecklistItem and UserChecklistItem

- app/checklist/views.py
Fixed permissions to ensure admin privileges. 
Tested to ensure normal behavior with admin.
> Fixing permissions

- app/decorators.py
Adding decorators for advisor and screener roles
Lmao
> add advisor_required and screener_required decorators

- app/__init__.py
- app/advisor/__init__.py
- app/advisor/views.py
- app/screener/__init__.py
- app/screener/views.py
- app/templates/advisor/index.html
- app/templates/screener/index.html
Fixes https://github.com/hack4impact/immigrant-defense-project/issues/8 by creating blueprints since previously screener and advisor (lawyer) routes were not defined. 
Tried logging in as a screener and an advisor. Currently a bug with screener being created as an advisor but still works.
> add advisor and screener blueprints

- app/decorators.py
- app/models/user.py
- tests/test_user_model.py
Role indices were broken before, so admins ended up having the same permissions as general users, etc. This PR fixes that.
Verified correct role ids through `data-dev.sqlite`.
> Fix role indices

- app/models/application.py
- app/models/user.py
- app/templates/application/dashboard.html
Move phone number to User model.
> Move phone_number to user model

- app/models/application.py
Different stages:
- UNMATCHED_PARTNER = 'unmatched_partner'
- MATCHED_PARTNER = 'matched_partner'
- COMPLETED_CHECKLIST = 'completed_checklist'
- IDP_ACCEPTED = 'idp_accepted'
- IDP_REJECTED = 'idp_rejected'
- MATCHED_ADVISOR = 'matched_legal_advisor'
> Add stage to application model

- app/models/application.py
- app/templates/application/dashboard.html
- app/templates/macros/nav_macros.html
> Added stage column for applications

- app/admin/views.py
- app/templates/admin/index.html
- app/templates/macros/nav_macros.html
> Change ScreeningQuestion to SurveyQuestion to match model!

- app/models/application.py
- app/models/user.py
> Fix relations between Application and User

- app/models/user.py
Add fake user checklist items.
Ran `add_fake_data` and checked `data-dev.sqlite`.
@sarahraines
> Add fake user checklist items

- app/application/forms.py
- app/application/views.py
- app/templates/application/dashboard.html
See above -- if i need to update `stage` too, lmk
local & check db using sql db browser
> Match applications -> legal advisor

- app/models/survey.py
- app/models/user.py
- app/survey/forms.py
- app/survey/views.py
- manage.py
* Expanded `SurveyQuestion`/`SurveyResponse` models
* Add `SurveyOption` model
* Generate fake data for these models
Ran `add_fake_data` and checked `data-dev.sqlite`.
@stephanieyshi
> Survey question/response/option model

- app/survey/views.py
- app/templates/survey/complete_survey.html
- app/templates/survey/stop_survey.html
- app/templates/survey/survey.html
checked cookies + ui testing 
@katiejiang
> making survey frontend look nicer + some user flow logic

- app/application/utils.py
Created functions to send acceptance and rejection emails to applicants. Created html template files, but still need to make the template.
> Accept / reject emails

- app/models/survey.py
- app/survey/forms.py
- app/survey/views.py
- app/templates/survey/manage.html
- app/templates/survey/new_question.html
Fix survey question bugs + add template for adding options to survey questions.
Ran on `http://localhost:5000/`
@stephanieyshi
> Survey options form

- app/survey/views.py
- app/templates/survey/new_question.html
> Populate edit question form with correct option values

- app/survey/forms.py
- app/survey/views.py
- app/templates/survey/new_question.html
> Add delete + edit options content

- app/advisor/forms.py
- app/advisor/views.py
- app/screener/forms.py
- app/screener/views.py
- app/templates/advisor/edit.html
- app/templates/advisor/profile.html
- app/templates/macros/nav_macros.html
- app/templates/screener/edit.html
- app/templates/screener/profile.html
> Added interface for screeners and advisors to see bio.
> Added nav-bar item for update profile.
> Created navigation between index, view profile, and edit profile.
> Did my task faster than I slide into those DMs :wink:
> Clicked through UI for both screener and advisor to see if it updated. It did so both on the interface and in the DB.
> Haha testing, what's that?
> @katiejiang
> display advisor and screener profiles

- app/survey/views.py
Unsure why these weren't here before. Addresses https://github.com/hack4impact/immigrant-defense-project/issues/52
Logged out of admin account and hit endpoints
> add admin_required decorators to survey routes

- app/admin/views.py
Fixes https://github.com/hack4impact/immigrant-defense-project/issues/62. necessary bc certain templates such as `application/dashboard.html` and `checklist/index.html` use admin.index. probably a better way to fix would be to do a frontend route rendering fix but i'm sleepy
> fix redirects for admin.index links

- app/templates/admin/index.html
- app/templates/macros/nav_macros.html
also reorganized the admin dashboard a little
> remove references to reminder.dashboard in frontend

- app/templates/survey/new_question.html
> Survey options

- app/models/user.py
- app/templates/advisor/profile.html
- app/templates/application/dashboard.html
- app/templates/application/profile.html
- app/templates/macros/profile_cards.html
- app/templates/screener/profile.html
> Update applicant bio with correct info, allow advisors to view applicants in table

- app/templates/application/dashboard.html
> Added column to view who legal advisor is

- app/account/forms.py
Removing phone number from registration form.
> deleted phone number from reg page

- app/application/forms.py
- app/application/views.py
- app/models/application.py
- app/templates/application/dashboard.html
> Partner matching in application!
